[package]
name = "desqta"
version = "1.0.0-rc2"
description = "DesQTA, a port of SEQTA to the Desktop"
authors = ["BetterSEQTA+ Project"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "desqta_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [ "macos-private-api", "devtools", "tray-icon"] }
tauri-plugin-opener = "2.5.0"
tauri-plugin-deep-link = "2"
tauri-plugin-autostart = "2.0.0"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs-next = "2.0"
base64 = "0.22.1"
urlencoding = "2"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"

rss = "2.0.12"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "multipart", "cookies"] }
tokio = { version = "1", features = ["full"] }
time = "0.3"
url = "2.5"
tauri-plugin-notification = "2"
tauri-plugin-single-instance = "2.3.4"
anyhow = "1.0.98"
xmltree = "0.11.0"
rayon = "1.8"
tokio-util = "0.7.15"
once_cell = "1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"
