name: Feature request
description: Suggest a new feature to be added or replaced in DesQTA
title: "[FR] "
labels: enhancement
body:
  - type: checkboxes
    attributes:
      label: Confirm
      options:
        - label: "I have searched existing issues to make sure this feature has not already been requested."
          required: true
        - label: "This feature request is not a duplicate of an existing bug report."
          required: false

  - type: input
    attributes:
      label: Related bug report link
      description: "If this feature request is related to a bug report, please insert the link here."
      placeholder: "https://github.com/BetterSEQTA/DesQTA/issues/..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Feature overview
        Provide a concise description of the feature and its purpose.

  - type: dropdown
    attributes:
      label: Feature type
      description: "Choose the type of feature."
      options:
        - Graphical
        - Functional
        - Performance
        - Not Sure
    validations:
      required: true

  - type: textarea
    attributes:
      label: Detailed description
      description: "Explain in detail what this feature should do."
      placeholder: "It would allow users to switch the theme to dark mode throughout the app."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: "Explain why this feature is useful and who it helps."
      placeholder: "Users who work at night or in low-light conditions would benefit from reduced eye strain."
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Priority
      description: "How important is this feature?"
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: false

  - type: textarea
    attributes:
      label: Alternatives considered
      description: "If applicable, describe any alternative solutions or workarounds."
      placeholder: "Currently users switch to external apps to reduce eye strain."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Possible implementation notes
      description: "If you have ideas about how this feature could be implemented, write them here."
      placeholder: "Add a theme toggle in the settings menu and save the preference locally."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: "Attach reference images, sketches, or any extra info that can help describe the feature."
      placeholder: "Screenshots, links, or diagrams."
    validations:
      required: false
