export const studyTips = [
    "If you can't learn at school, study more at home!",
    "Believe it or not, school is for learning.",
    "Nahh, I'll get this done tomorrow.",
    "Procrastination leads to depression and anxiety...",
    "You need to keep assignments in the important an not urgent category, Don't wait till the last minute to work!",
    "Gantt charts are an awesome way to organise your tasks, try it sometime!",
    "Try rewarding good study with a treat to enforce good patterns and habits.",
    "Listening to music only helps you focus if it is lyricless.",
    "Cramming is only useful if your notes are organised.",
    "Organizing your thoughts can help you to learn better.",
    "If you read the textbook you will learn something.",
    "Learning is not a passive activity.",
    "Study groups work best when at least one person actually studied.",
    "Break tasks into 25-minute focus sessions.",
    "Start with high-priority items due soon.",
    "Keep your task titles clear and specific.",
    "Use the Pomodoro Technique: 25 minutes work, 5 minutes break.",
    "Create a dedicated study space free from distractions.",
    "Review your notes within 24 hours of taking them.",
    "Use active recall instead of just re-reading.",
    "Teach someone else what you've learned.",
    "Take regular breaks to maintain concentration.",
    "Use flashcards for memorizing key concepts.",
    "Study in different locations to improve retention.",
    "Practice spaced repetition for long-term memory.",
    "Set specific, achievable daily study goals.",
    "Use mind maps to visualize complex topics.",
    "Study the most challenging subjects when you're most alert.",
    "Create a consistent study schedule and stick to it.",
    "Use background music or white noise if it helps you focus.",
    "Eliminate your phone and social media during study time.",
    "Take handwritten notes to improve comprehension.",
    "Use the Feynman Technique: explain concepts in simple terms.",
    "Form study groups with motivated classmates.",
    "Practice past exams and sample questions.",
    "Use mnemonics to remember lists and sequences.",
    "Get enough sleep - it's crucial for memory consolidation.",
    "Exercise regularly to boost brain function.",
    "Stay hydrated and eat brain-healthy foods.",
    "Use different colors for organizing notes and concepts.",
    "Create acronyms to remember key information.",
    "Study before bed to enhance memory retention.",
    "Use the SQ3R method: Survey, Question, Read, Recite, Review.",
    "Break large projects into smaller, manageable chunks.",
    "Use timers to stay focused and track progress.",
    "Create visual aids like charts and diagrams.",
    "Practice explaining concepts out loud.",
    "Use the 80/20 rule: focus on the most important 20%.",
    "Take practice tests under exam conditions.",
    "Review mistakes and understand why they happened.",
    "Use spaced learning: study a little bit every day.",
    "Create connections between new and existing knowledge.",
    "Use the Cornell Note-taking system.",
    "Study in natural light when possible.",
    "Keep a study journal to track your progress.",
    "Use online resources and educational videos.",
    "Form study partnerships for accountability.",
    "Create rhymes or songs to remember information.",
    "Use the method of loci (memory palace technique).",
    "Take breaks every 45-90 minutes.",
    "Study similar subjects at different times to avoid confusion.",
    "Use highlighters strategically, not excessively.",
    "Create your own practice questions.",
    "Study in short, frequent sessions rather than long cramming.",
    "Use positive self-talk and visualization.",
    "Reward yourself for reaching study milestones.",
    "Keep your study area clean and organized.",
    "Use apps and tools to block distracting websites.",
    "Study with purpose - know why you're learning something.",
    "Create summary sheets for quick review.",
    "Use different study methods for different types of content.",
    "Practice retrieval: test yourself without looking at notes.",
    "Study in groups for discussion-based subjects.",
    "Use analogies to understand complex concepts.",
    "Take care of your physical health to support mental performance.",
    "Use the rubber duck debugging method for problem-solving.",
    "Create a pre-study routine to get in the zone.",
    "Use background apps that simulate library or café sounds.",
    "Study the hardest material when your energy is highest.",
    "Want to focus better? Try cocaine!",
    "Use the two-minute rule: if it takes less than 2 minutes, do it now.",
    "Create a study playlist that doesn't include TikTok sounds.",
    "Use the 'teach your pet' method - they're great listeners and won't judge your mistakes.",
    "Remember: DesQTA won't judge you for checking your grades 47 times a day.",
    "Pro tip: Highlighters are not meant to color entire textbooks yellow.",
    "Study in the library where WiFi is slow enough to prevent distractions.",
    "Why did the student use DesQTA? Because it's better than carrier pigeons for assignments!",
    "Create study rewards that aren't just 'one more episode' on Netflix.",
    "Use the 'explain it to your rubber duck' debugging method for any subject.",
    "SEQTA notifications: the only notifications you actually want to receive.",
    "Study fact: Coffee is not a food group, but we understand the confusion.",
    "Try the 'phone in another room' technique - revolutionary, we know.",
    "DesQTA: Making procrastination slightly more organized since today.",
    "Use active reading: argue with your textbook, it builds character.",
    "Study groups work best when at least one person actually studied.",
    "Remember: Your future self will thank you (and probably still be tired).",
    "SEQTA portals: Like regular portals, but with more assignments and less magic.",
    "Create mnemonics that don't involve inappropriate acronyms (we see you).",
    "Study in natural light - your vampire aesthetic can wait until after exams.",
    "Why do students love DesQTA? Because it actually works when you need it to!",
    "Use the Cornell note system, not the 'scribbled panic' system.",
    "Take breaks: Your brain needs them more than your Instagram feed needs you.",
    "Study tip: 'I'll remember this' is not a valid note-taking strategy.",
    "SEQTA assessments: Keeping students humble since forever.",
    "Use flashcards, not flash judgments about your study abilities.",
    "Study in silence, or with lo-fi hip hop like every other student on Earth.",
    "DesQTA: Because sometimes you need to organize your organization apps.",
    "Practice retrieval: Quiz yourself without Google - shocking, we know.",
    "Why did the student switch to DesQTA? Their old system was more confused than they were!",
    "Study consistently: Cramming is like brushing your teeth once a month.",
    "Use the Pomodoro Technique, not the 'Procrastination Technique'.",
    "SEQTA messages: The only DMs that actually matter for your future.",
    "Create a study schedule and actually follow it (revolutionary concept).",
    "Study fact: Highlighting everything is the same as highlighting nothing.",
    "DesQTA tasks: Like regular tasks, but with more color-coding and less crying.",
    "Use spaced repetition, not 'spaced out' repetition.",
    "Take notes by hand - your future carpal tunnel-free self will thank you.",
    "Why do teachers love SEQTA? Because it keeps track of things they'd forget too!",
    "Study in chunks: Your brain is not a garbage disposal for information.",
    "Use the 'teach your houseplant' method - they're great listeners and won't interrupt.",
    "DesQTA priorities: Finally, a priority system that makes sense (unlike your life).",
    "Practice past papers: Because future you needs to know what past you should have studied.",
    "Study tip: Energy drinks are not a substitute for actual energy or actual studying.",
    "SEQTA timetables: Making 'what class do I have next?' a thing of the past.",
    "Use mind maps instead of mind blanks during exams.",
    "Now with less learning!",
    "Study groups: Where 'let's study' becomes 'let's complain about studying'.",
    "DesQTA: Turning your chaotic student life into organized chaos.",
    "Review notes within 24 hours, not 24 minutes before the exam.",
    "Why did the student love DesQTA's study page? Because it actually helped them study!",
    "Use the Feynman Technique: If you can't explain it simply, you don't understand it yet.",
    "Study in different locations: Your bedroom is not the academic powerhouse you think it is.",
    "SEQTA notifications: The only notifications that actually improve your life.",
    "Create acronyms that you'll actually remember next week.",
    "Study fact: 'I'll start tomorrow' is not a study strategy, it's a lifestyle choice.",
    "DesQTA subtasks: Breaking down your breakdown into manageable pieces.",
    "Use active recall: Test yourself like your life depends on it (because your GPA does).",
    "Study with purpose: 'Because I have to' is not a purpose, it's a cry for help.",
    "Why do students procrastinate less with DesQTA? Because it makes procrastination feel organized!",
    "Take care of your health: Dead students don't graduate (this is not medical advice).",
    "Use the 'rubber duck' method: Explain concepts to inanimate objects with confidence.",
    "SEQTA assessments: Like regular assessments, but with more existential dread.",
    "Study consistently: Your brain prefers steady progress over panic-induced marathons.",
    "DesQTA: Making 'I forgot about that assignment' a thing of the past.",
    "Create a pre-study ritual that doesn't involve checking social media 'just once'.",
    "Study tip: Your bed is for sleeping, not for pretending to study while scrolling TikTok."
  ];
